name: erasmus_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^0.1.2
  #To open the browser
  url_launcher: ^4.0.3
  #Json
  json_annotation: ^2.0.0
  #Markdown
  flutter_markdown: ^0.2.0
  #To get file paths on IOS and Android
  path_provider: ^0.4.1
  #To get permissions for writing to the file system
  simple_permissions: ^0.1.9
  #Random uuids
  uuid: ^1.0.3
  #Date formatting
  intl: ^0.15.7
  #Rich text editor
  zefyr:
    path: ../zefyr/packages/zefyr/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  json_serializable: ^2.0.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - 'assets/images/'
  - 'assets/countries/'
  - 'assets/countries/germany/'
  - 'assets/countries/greece/'
  - 'assets/countries/lithuania/'
  - 'assets/countries/slovakia/'
  - 'assets/countries/turkey/'
  - 'assets/schools/'
  - 'assets/schools/hessenwaldschule/'
  - 'assets/schools/gymnasium_chalkida/'
  - 'assets/schools/gymnazium/'
  - 'assets/schools/juliaus_janonio_gimnazija/'
  - 'assets/schools/muhittin_mustafa_boecek_anadolu_lisesi/'

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
